default_language_version:
  python: python3.12

# Exclude generated or external data from all hooks
exclude: |
  ^prometheus_data/|
  ^uv\.lock$

repos:
  # Ruff lint and format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        files: ^(src|tests)/
      - id: ruff-format
        files: ^(src|tests)/

  # Codespell for common spelling mistakes
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["--quiet-level=2"]
        types_or: [python, markdown, rst, text]
        files: ^(src|tests|docs)/|^README\.md$

  # Mypy static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive"]
        files: ^(src|tests)/
