global:
  # Set global scrape intervals
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  # Configure alertmanager settings
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: []
scrape_configs:
  - job_name: "fastapi-app"
    # Scrape FastAPI app metrics
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: "fastapi"
    # Scrape metrics from web:8000
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      -targets: ["web:8000"]
